# Generated by Django 2.0 on 2019-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='idconfig',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('config', models.CharField(max_length=1000)),
                ('capturedserver', models.CharField(max_length=200)),
                ('interval', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rtsp',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('res_name', models.CharField(max_length=200)),
                ('camid', models.CharField(max_length=200)),
                ('rtsp', models.CharField(max_length=1000)),
                ('cam_name', models.CharField(max_length=200)),
            ],
        ),
    ]
